# Generated by Django 3.2.12 on 2022-08-09 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soundsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
