# Generated by Django 2.2.7 on 2020-11-24 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parrot_control', '0007_commandcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parrotcommand',
            name='category_id',
        ),
        migrations.AddField(
            model_name='parrotcommand',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='parrot_control.CommandCategory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commandcategory',
            name='button_color',
            field=models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('yellow', 'Yellow')], default='blue', max_length=32),
        ),
    ]
