# Generated by Django 2.2.7 on 2020-10-25 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parrot_control', '0003_auto_20200910_0325'),
    ]

    operations = [
        migrations.AddField(
            model_name='parrotcommand',
            name='voice_relative_path',
            field=models.CharField(default='./ros/some/command.mp3', max_length=512),
            preserve_default=False,
        ),
    ]
