# Generated by Django 2.2.7 on 2020-11-24 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parrot_control', '0008_auto_20201124_0157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commandcategory',
            options={'verbose_name_plural': 'Command Categories'},
        ),
        migrations.AlterModelOptions(
            name='commandconfig',
            options={'verbose_name_plural': 'Commands Config'},
        ),
        migrations.AlterModelOptions(
            name='parrotcommand',
            options={'verbose_name_plural': 'Parrot Commands'},
        ),
        migrations.RemoveField(
            model_name='parrotcommand',
            name='priority',
        ),
        migrations.AddField(
            model_name='commandcategory',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='commandcategory',
            name='button_color',
            field=models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('yellow', 'Yellow'), ('violet', 'Violet'), ('orange', 'Orange'), ('black', 'Black'), ('gray', 'Gray')], default='blue', max_length=32),
        ),
    ]
