# Generated by Django 2.2.7 on 2020-12-01 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parrot_control', '0013_auto_20201124_0331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commandconfig',
            name='voice_path_postfix',
        ),
        migrations.RemoveField(
            model_name='commandconfig',
            name='voice_path_prefix',
        ),
        migrations.AddField(
            model_name='commandconfig',
            name='blue_parrot_voice_path_postfix',
            field=models.CharField(blank=True, default='.wav', max_length=256),
        ),
        migrations.AddField(
            model_name='commandconfig',
            name='blue_parrot_voice_path_prefix',
            field=models.CharField(blank=True, default='./', max_length=256),
        ),
        migrations.AddField(
            model_name='commandconfig',
            name='red_parrot_voice_path_postfix',
            field=models.CharField(blank=True, default='.wav', max_length=256),
        ),
        migrations.AddField(
            model_name='commandconfig',
            name='red_parrot_voice_path_prefix',
            field=models.CharField(blank=True, default='./', max_length=256),
        ),
    ]
