# Generated by Django 3.2.12 on 2022-11-11 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parrot_control', '0015_auto_20221111_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='parrotcommand',
            name='interface_button_emoji',
            field=models.CharField(choices=[('😂', '😂'), ('🙄', '🙄'), ('😄', '😄'), ('🙁', '🙁'), ('😱', '😱'), ('😎', '😎'), ('😡', '😡'), ('😅', '😅'), ('😐', '😐'), ('🤩', '🤩'), ('😊', '😊'), ('🤭', '🤭'), ('😧', '😧'), ('😳', '😳'), ('😌', '😌')], default='😳', max_length=25),
            preserve_default=False,
        ),
    ]
