// Generated by gencpp from file multi_parrot_blue/BlueParrotResponse.msg
// DO NOT EDIT!


#ifndef MULTI_PARROT_BLUE_MESSAGE_BLUEPARROTRESPONSE_H
#define MULTI_PARROT_BLUE_MESSAGE_BLUEPARROTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace multi_parrot_blue
{
template <class ContainerAllocator>
struct BlueParrotResponse_
{
  typedef BlueParrotResponse_<ContainerAllocator> Type;

  BlueParrotResponse_()
    : result()  {
    }
  BlueParrotResponse_(const ContainerAllocator& _alloc)
    : result(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::multi_parrot_blue::BlueParrotResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::multi_parrot_blue::BlueParrotResponse_<ContainerAllocator> const> ConstPtr;

}; // struct BlueParrotResponse_

typedef ::multi_parrot_blue::BlueParrotResponse_<std::allocator<void> > BlueParrotResponse;

typedef boost::shared_ptr< ::multi_parrot_blue::BlueParrotResponse > BlueParrotResponsePtr;
typedef boost::shared_ptr< ::multi_parrot_blue::BlueParrotResponse const> BlueParrotResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::multi_parrot_blue::BlueParrotResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::multi_parrot_blue::BlueParrotResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::multi_parrot_blue::BlueParrotResponse_<ContainerAllocator1> & lhs, const ::multi_parrot_blue::BlueParrotResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::multi_parrot_blue::BlueParrotResponse_<ContainerAllocator1> & lhs, const ::multi_parrot_blue::BlueParrotResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace multi_parrot_blue

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::multi_parrot_blue::BlueParrotResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::multi_parrot_blue::BlueParrotResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::multi_parrot_blue::BlueParrotResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::multi_parrot_blue::BlueParrotResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::multi_parrot_blue::BlueParrotResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::multi_parrot_blue::BlueParrotResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::multi_parrot_blue::BlueParrotResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c22f2a1ed8654a0b365f1bb3f7ff2c0f";
  }

  static const char* value(const ::multi_parrot_blue::BlueParrotResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc22f2a1ed8654a0bULL;
  static const uint64_t static_value2 = 0x365f1bb3f7ff2c0fULL;
};

template<class ContainerAllocator>
struct DataType< ::multi_parrot_blue::BlueParrotResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "multi_parrot_blue/BlueParrotResponse";
  }

  static const char* value(const ::multi_parrot_blue::BlueParrotResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::multi_parrot_blue::BlueParrotResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string result\n"
;
  }

  static const char* value(const ::multi_parrot_blue::BlueParrotResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::multi_parrot_blue::BlueParrotResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BlueParrotResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::multi_parrot_blue::BlueParrotResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::multi_parrot_blue::BlueParrotResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MULTI_PARROT_BLUE_MESSAGE_BLUEPARROTRESPONSE_H
