// Generated by gencpp from file multi_parrot_blue/BlueParrotRequest.msg
// DO NOT EDIT!


#ifndef MULTI_PARROT_BLUE_MESSAGE_BLUEPARROTREQUEST_H
#define MULTI_PARROT_BLUE_MESSAGE_BLUEPARROTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace multi_parrot_blue
{
template <class ContainerAllocator>
struct BlueParrotRequest_
{
  typedef BlueParrotRequest_<ContainerAllocator> Type;

  BlueParrotRequest_()
    : command()  {
    }
  BlueParrotRequest_(const ContainerAllocator& _alloc)
    : command(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _command_type;
  _command_type command;





  typedef boost::shared_ptr< ::multi_parrot_blue::BlueParrotRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::multi_parrot_blue::BlueParrotRequest_<ContainerAllocator> const> ConstPtr;

}; // struct BlueParrotRequest_

typedef ::multi_parrot_blue::BlueParrotRequest_<std::allocator<void> > BlueParrotRequest;

typedef boost::shared_ptr< ::multi_parrot_blue::BlueParrotRequest > BlueParrotRequestPtr;
typedef boost::shared_ptr< ::multi_parrot_blue::BlueParrotRequest const> BlueParrotRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::multi_parrot_blue::BlueParrotRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::multi_parrot_blue::BlueParrotRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::multi_parrot_blue::BlueParrotRequest_<ContainerAllocator1> & lhs, const ::multi_parrot_blue::BlueParrotRequest_<ContainerAllocator2> & rhs)
{
  return lhs.command == rhs.command;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::multi_parrot_blue::BlueParrotRequest_<ContainerAllocator1> & lhs, const ::multi_parrot_blue::BlueParrotRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace multi_parrot_blue

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::multi_parrot_blue::BlueParrotRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::multi_parrot_blue::BlueParrotRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::multi_parrot_blue::BlueParrotRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::multi_parrot_blue::BlueParrotRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::multi_parrot_blue::BlueParrotRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::multi_parrot_blue::BlueParrotRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::multi_parrot_blue::BlueParrotRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cba5e21e920a3a2b7b375cb65b64cdea";
  }

  static const char* value(const ::multi_parrot_blue::BlueParrotRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcba5e21e920a3a2bULL;
  static const uint64_t static_value2 = 0x7b375cb65b64cdeaULL;
};

template<class ContainerAllocator>
struct DataType< ::multi_parrot_blue::BlueParrotRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "multi_parrot_blue/BlueParrotRequest";
  }

  static const char* value(const ::multi_parrot_blue::BlueParrotRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::multi_parrot_blue::BlueParrotRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string command\n"
;
  }

  static const char* value(const ::multi_parrot_blue::BlueParrotRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::multi_parrot_blue::BlueParrotRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.command);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BlueParrotRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::multi_parrot_blue::BlueParrotRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::multi_parrot_blue::BlueParrotRequest_<ContainerAllocator>& v)
  {
    s << indent << "command: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.command);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MULTI_PARROT_BLUE_MESSAGE_BLUEPARROTREQUEST_H
