# Generated by Django 3.2.12 on 2022-08-21 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soundsapp', '0004_auto_20220821_1301'),
        ('hooshangapp', '0003_alter_emotionmodel_face'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotionmodel',
            name='face',
            field=models.CharField(blank=True, default='normal', max_length=25),
        ),
        migrations.AlterField(
            model_name='emotionmodel',
            name='sound',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='soundsapp.song'),
        ),
    ]
