# Generated by Django 3.2.12 on 2022-08-21 08:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hooshangapp', '0004_auto_20220821_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotionmodel',
            name='interface_button_emoji',
            field=models.CharField(choices=[('Laugh', 'bi bi-emoji-laughing'), ('Laugh', 'bi bi-emoji-laughing')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
