# Generated by Django 3.2.12 on 2022-08-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hooshangapp', '0007_auto_20220821_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotionmodel',
            name='interface_button_emoji',
            field=models.CharField(choices=[('bi bi-emoji-laugh', '😂'), ('bi bi-emoji-neutral', '🙄'), ('bi bi-emoji-laughing', '😄'), ('bi bi-emoji-frown', '🙁'), ('bi bi-emoji-crying', '😭'), ('bi bi-emoji-surprised', '😳'), ('bi bi-emoji-sad', '😥'), ('bi bi-emoji-shy', '😅'), ('bi bi-emoji-love', '\U0001f970'), ('bi bi-emoji-sunglasses', '😎'), ('bi bi-emoji-angry', '😡'), ('bi bi-emoji-smile', '😊')], max_length=25),
        ),
    ]
