# Generated by Django 3.2.12 on 2022-09-08 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hooshangapp', '0013_alter_emotionmodel_interface_button_emoji'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotionmodel',
            name='interface_button_emoji',
            field=models.CharField(choices=[('😂', '😂'), ('🙄', '🙄'), ('😄', '😄'), ('🙁', '🙁'), ('😱', '😱'), ('😎', '😎'), ('😡', '😡'), ('😊', '😊')], max_length=25),
        ),
    ]
