# Generated by Django 2.2.7 on 2020-08-24 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParrotCommand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=40)),
                ('category_id', models.IntegerField(default=0)),
                ('tag', models.CharField(choices=[('P_M', 'Parrot Movement'), ('P_V', 'Parrot Voice'), ('P_A', 'Parrot Auto')], max_length=4)),
                ('arg', models.IntegerField(unique=True)),
                ('priority', models.IntegerField(default=10)),
                ('voice_file', models.FileField(blank=True, upload_to='')),
                ('perform_time', models.IntegerField(default=5)),
            ],
        ),
    ]
