# Generated by Django 2.2.7 on 2020-08-24 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parrot_control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parrotcommand',
            name='tag',
            field=models.CharField(choices=[('P_M', 'Parrot Movement'), ('P_V', 'Parrot Voice')], max_length=4),
        ),
    ]
