# Generated by Django 2.2.7 on 2020-09-10 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parrot_control', '0002_auto_20200824_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='parrotcommand',
            name='parrot_0',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='parrotcommand',
            name='parrot_1',
            field=models.BooleanField(default=True),
        ),
    ]
