# Generated by Django 2.2.7 on 2020-11-24 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parrot_control', '0006_auto_20201124_0133'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=20, unique=True)),
                ('button_color', models.CharField(choices=[('Red', 'red'), ('Blue', 'blue'), ('Green', 'green'), ('Yellow', 'yellow')], default='blue', max_length=32)),
            ],
        ),
    ]
