# Generated by Django 2.2.7 on 2020-11-24 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parrot_control', '0009_auto_20201124_0242'),
    ]

    operations = [
        migrations.AddField(
            model_name='parrotcommand',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
