# Generated by Django 2.2.7 on 2020-11-24 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parrot_control', '0011_auto_20201124_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parrotcommand',
            name='voice_file_name',
            field=models.CharField(blank=True, default='_', max_length=512),
        ),
    ]
