# Generated by Django 3.2.12 on 2022-11-11 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parrot_control', '0018_alter_parrotcommand_interface_button_emoji'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parrotcommand',
            name='interface_button_emoji',
            field=models.CharField(choices=[('💃', '💃'), ("'😃🙂'", "'😃🙂'"), ("'😛😝'", "'😛😝'"), ("'😛'", "'😛'"), ("'😝'", "'😝'"), ("'😃'", "'😃'"), ("'🙂'", "'🙂'")], max_length=25),
        ),
    ]
