# Generated by Django 3.2.12 on 2022-08-21 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soundsapp', '0003_auto_20220809_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='song',
            name='image',
        ),
        migrations.AddField(
            model_name='song',
            name='description',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(default='Unknown', max_length=20),
        ),
    ]
