# Generated by Django 3.2.12 on 2023-07-25 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmotionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face', models.CharField(blank=True, default='normal', max_length=25, unique=True)),
                ('face_video_url', models.CharField(blank=True, default='http://172.18.133.241:3000/mahta.mp4', max_length=200)),
                ('interface_button_emoji', models.CharField(choices=[('😂', '😂'), ('🙄', '🙄'), ('😄', '😄'), ('🙁', '🙁'), ('😱', '😱'), ('😎', '😎'), ('😡', '😡'), ('😅', '😅'), ('😐', '😐'), ('🤩', '🤩'), ('😊', '😊'), ('🤭', '🤭'), ('😧', '😧'), ('😳', '😳'), ('😌', '😌')], max_length=25)),
            ],
        ),
    ]
