# Generated by Django 3.2.12 on 2022-08-17 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('soundsapp', '0003_auto_20220809_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmotionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face', models.CharField(blank=True, default='normal', max_length=25)),
                ('sound', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='soundsapp.song')),
            ],
        ),
    ]
