# Generated by Django 3.2.12 on 2022-08-09 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soundsapp', '0002_alter_song_id'),
        ('hooshangapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmotionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face', models.CharField(blank=True, default='normal', max_length=25)),
                ('sound', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='soundsapp.song')),
            ],
        ),
        migrations.DeleteModel(
            name='HooshangCommands',
        ),
    ]
