# Generated by Django 3.2.12 on 2022-08-21 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hooshangapp', '0005_emotionmodel_interface_button_emoji'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emotionmodel',
            name='face_video_url',
        ),
        migrations.RemoveField(
            model_name='emotionmodel',
            name='interface_button_emoji',
        ),
    ]
