# Generated by Django 3.2.12 on 2022-08-21 10:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hooshangapp', '0006_auto_20220821_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotionmodel',
            name='face_video_url',
            field=models.CharField(blank=True, default='http://172.18.133.241:3000/mahta.mp4', max_length=200),
        ),
        migrations.AddField(
            model_name='emotionmodel',
            name='interface_button_emoji',
            field=models.CharField(choices=[('bi bi-emoji-laughing', 'L'), ('bi bi-emoji-neutral', 'N'), ('bi bi-emoji-', 'N'), ('bi bi-emoji-neutral', 'N'), ('bi bi-emoji-neutral', 'N'), ('bi bi-emoji-neutral', 'N'), ('bi bi-emoji-neutral', 'N')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
