# Generated by Django 3.2.12 on 2022-09-08 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hooshangapp', '0014_alter_emotionmodel_interface_button_emoji'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotionmodel',
            name='interface_button_emoji',
            field=models.CharField(choices=[('😂', '😂'), ('🙄', '🙄'), ('😄', '😄'), ('🙁', '🙁'), ('😱', '😱'), ('😎', '😎'), ('😡', '😡'), ('\U0001f979', '\U0001f979'), ('😅', '😅'), ('\U0001f929', '\U0001f929'), ('😊', '😊'), ('😐', '😐'), ('\U0001f92d', '\U0001f92d'), ('😧', '😧'), ('😳', '😳'), ('😍', '😍'), ('😌', '😌')], max_length=25),
        ),
    ]
