# Generated by Django 3.2.12 on 2022-08-21 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hooshangapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotionmodel',
            name='face_video_url',
            field=models.CharField(blank=True, default='http://172.18.133.241:3000/mahta.mp4', max_length=200),
        ),
    ]
